---
title: "Interactivity_Plotlyandflexdashboard"
author: "Candace Haghighi"
date: "11/1/2017"
output: html_document
---

>Libraries 

```{r}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
```

```{r}
airbnb = read_csv("./Data/nyc_airbnb.zip") %>%
  clean_names() %>%
  rename(boro = neighbourhood_group) %>%
  mutate(rating = review_scores_location/2) %>%
  filter(boro == "Manhattan", 
     room_type == "Entire home/apt",
     price > 100 & price < 400) 
```

##Plotly scatterplot. "\N" means create a new line. 

```{r}
airbnb %>%
  mutate(hover_text = str_c("Price: $", price)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, color = ~price,
          alpha = 0.5, 
          text = ~hover_text, type = "scatter", mode = "markers")
```

##Plotly boxplot

```{r}
airbnb %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(x = ~neighbourhood, y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2" )
```

##Plotly barchart

```{r}
airbnb %>%
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>%
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
```

##GGPlotly

```{r}
scatter_ggplot = airbnb %>%
  ggplot(aes(x = longitude, y = latitude, color = price)) +
  geom_point(alpha = 0.25) +
  scale_color_viridis() +
  coord_cartesian() +
  theme_classic()
ggplotly(scatter_ggplot)
```

##Dashboards. R studio is not doing the right thing locally. Workaround - if want to use dashboard, rebuild everytime. 

```{r}
library(flexdashboard)
```